version: '3'

services:
  web:
    restart: always
    image: anettoph/my-uwsgi-nginx-flask:v1
    container_name: gg-aly-test1-web
    ports:
      - "80:80"
      - "443:443"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./www/gg-py-test1:/app
    environment:
      STATIC_URL: /app/static

  postgres:
    restart: always
    build: ./postgres
    container_name: gg-aly-test1-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
