"""Initial migration.

Revision ID: a2a0e0e703d0
Revises: 
Create Date: 2021-03-09 13:40:51.107018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a0e0e703d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('clanname', sa.String(length=64), nullable=True),
    sa.Column('accounttype', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_clanname'), 'accounts', ['clanname'], unique=False)
    op.create_index(op.f('ix_accounts_nickname'), 'accounts', ['nickname'], unique=True)
    op.create_index(op.f('ix_accounts_rank'), 'accounts', ['rank'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_rank'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_nickname'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_clanname'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
